CREATE TABLE Addresses(
ID INT IDENTITY PRIMARY KEY,
RUA VARCHAR(120) NOT NULL,
BAIRRO VARCHAR(120) NULL,
CIDADE VARCHAR(100) NOT NULL,
UF CHAR(2) NULL,
CEP VARCHAR(16) NULL,
PAIS VARCHAR(20) NOT NULL
)

CREATE TABLE Providers
(
ID INT PRIMARY KEY IDENTITY,
CNPJ VARCHAR(11) UNIQUE NOT NULL,
RAZAOSOCIAL VARCHAR(70) NOT NULL,
NOMEFANTASIA VARCHAR(70) NULL,
NOMECONTATO VARCHAR(70) NOT NULL,
EMAIL VARCHAR (60) NOT NULL,
TELEFONE1 VARCHAR (15) NOT NULL,
TELEFONE2 VARCHAR (15) DEFAULT NULL,
DATA_CADASTRO DATETIME DEFAULT GETDATE() NOT NULL,
ENDERECOID INT CONSTRAINT fk_Provider_Address
	     FOREIGN KEY REFERENCES Addresses(ID) NOT NULL,
ATIVO BIT DEFAULT 1 NOT NULL,
)

CREATE TABLE Users (
ID INT IDENTITY PRIMARY KEY,
NOME VARCHAR(70) NOT NULL,
CPF CHAR (11) NOT NULL,
RG VARCHAR (15) NOT NULL,
EMAIL VARCHAR (60) NOT NULL,
TELEFONE1 VARCHAR (15) NOT NULL,
TELEFONE2 VARCHAR (15) DEFAULT NULL,
ENDERECOID INT CONSTRAINT fk_User_Address
         FOREIGN KEY REFERENCES Addresses(ID) NOT NULL,
DATA_CADASTRO DATETIME DEFAULT GETDATE() NOT NULL,
ISADMIN BIT NOT NULL DEFAULT 0,
SENHA VARCHAR (50) NOT NULL,
ATIVO BIT DEFAULT 1,
)

CREATE TABLE Customers (
ID INT IDENTITY PRIMARY KEY,
NOME VARCHAR(70) NOT NULL,
CPF CHAR (11) NOT NULL,
RG VARCHAR (15) NOT NULL,
TELEFONE1 VARCHAR (15) NOT NULL,
TELEFONE2 VARCHAR (15) DEFAULT NULL,
EMAIL VARCHAR (60) NOT NULL,
ENDERECOID INT CONSTRAINT fk_Customer_Address
         FOREIGN KEY REFERENCES Addresses(ID),
DATA_CADASTRO DATETIME DEFAULT GETDATE() NOT NULL,
ATIVO BIT DEFAULT 1 NOT NULL,
)

CREATE TABLE Rooms(
ID INT IDENTITY PRIMARY KEY,
BLOCO VARCHAR(10) NOT NULL,
NOME VARCHAR(6) NOT NULL,
VALOR_DIARIA FLOAT(10) NOT NULL,
DATA_CADASTRO DATETIME DEFAULT GETDATE() NOT NULL,
RESERVADO BIT NOT NULL DEFAULT 1,
ATIVO BIT DEFAULT 1,
)

CREATE TABLE RoomCheckIn(
ID INT IDENTITY PRIMARY KEY,
QUARTOID INT CONSTRAINT fk_ROOMCHECKIN_ROOM
         FOREIGN KEY REFERENCES Rooms(ID) NOT NULL,
CUSTOMERID INT CONSTRAINT fk_ROOMCHECKIN_CUSTOMER
         FOREIGN KEY REFERENCES Customers(ID) NOT NULL,
FUNCIONARIOID INT CONSTRAINT fk_ROOMCHECKIN_USER
		 FOREIGN KEY REFERENCES Users(ID) NOT NULL,
DATA_CADASTRO DATETIME DEFAULT GETDATE() NOT NULL,
DATA_PREVISTA_SAIDA DATE NULL,
ATIVO BIT DEFAULT 1,
)

CREATE TABLE RoomCheckOut(
ID INT IDENTITY PRIMARY KEY,
CHECKINID INT CONSTRAINT fk_ROOMCHECKIN_ROOMCHECKOUT
         FOREIGN KEY REFERENCES RoomCheckIn(ID) NOT NULL,
DATA_CADASTRO DATETIME DEFAULT GETDATE() NOT NULL,
ATIVO BIT DEFAULT 1,
)

CREATE TABLE RoomServices(
ID INT IDENTITY PRIMARY KEY,
QUARTOID INT CONSTRAINT fk_ROOM_ROOMSERVICE
         FOREIGN KEY REFERENCES Rooms(ID),
FUNCIONARIOID INT CONSTRAINT fk_USER_ROOMSERVICE
         FOREIGN KEY REFERENCES Users(ID),
DATA_CADASTRO DATETIME DEFAULT GETDATE() NOT NULL,
LIMPEZA_CONCLUIDA BIT DEFAULT 0,
ATIVO BIT DEFAULT 1,
)

CREATE TABLE  Reservations (
ID INT IDENTITY PRIMARY KEY,
QUARTOID INT CONSTRAINT fk_ROOM_RESERVATION
         FOREIGN KEY REFERENCES Rooms(ID),
CUSTOMERID INT CONSTRAINT fk_CUSTOMER_RESERVATION
         FOREIGN KEY REFERENCES Customers(ID) NOT NULL,
FUNCIONARIOID INT CONSTRAINT fk_USER_RESERVATION
         FOREIGN KEY REFERENCES Users(ID),
DATA_CADASTRO DATETIME DEFAULT GETDATE() NOT NULL,
DATA_RESERVA DATE NOT NULL,
STATUS_RESERVA BIT DEFAULT 1,
ATIVO BIT DEFAULT 1,
)

--------------------------------------------------------------------------------

CREATE TABLE Categories 
(
ID INT PRIMARY KEY IDENTITY,
DATA_CADASTRO DATETIME DEFAULT GETDATE() NOT NULL,
NOME VARCHAR(60) NOT NULL,
ATIVO BIT DEFAULT 1,
)

CREATE TABLE Products
(
ID INT PRIMARY KEY IDENTITY,
NOME VARCHAR(70) NOT NULL,
DESCRICAO VARCHAR(150) NOT NULL,
PRECO FLOAT NOT NULL,
QTDESTOQUE FLOAT NOT NULL,
UNIDADEMEDIDA INT NOT NULL,
DATAVALIDADE DATE CHECK (DATAVALIDADE < GETDATE()) NOT NULL,
DATACADASTRO DATETIME DEFAULT GETDATE() NOT NULL,
CATEGORIAID INT NOT NULL,
	CONSTRAINT FK_PRODUCTS_CATEGORIES FOREIGN KEY (CATEGORIAID) 
	REFERENCES Categories,
ATIVO BIT DEFAULT 1 NOT NULL,
)

CREATE TABLE Product_Entry
(
	ID INT PRIMARY KEY IDENTITY,
	DATA_CADASTRO DATETIME DEFAULT GETDATE() NOT NULL
)

CREATE TABLE Entry_Items
(
	ID INT PRIMARY KEY IDENTITY,
	PRODUTOID INT NOT NULL,
	CONSTRAINT FK_PRODUCT_ITEM FOREIGN KEY (PRODUTOID) 
	REFERENCES Products,
	QUANTIDADE INT NOT NULL, 
	CUSTO FLOAT NOT NULL,
	PRODUCT_ENTRYID INT NOT NULL CONSTRAINT FK_PROUCT_ENTRY FOREIGN KEY
	REFERENCES Product_Entry,
	DATA_CADASTRO DATETIME DEFAULT GETDATE() NOT NULL,
	ATIVO BIT DEFAULT 1 NOT NULL,
)

CREATE TABLE Provider_has_Product
(
	ID INT IDENTITY,
	PRODUCTID INT NOT NULL,
	CONSTRAINT FK_PRODUCT_PROVIDERS FOREIGN KEY (PRODUCTID) 
	REFERENCES Products,
	PROVIDERID INT NOT NULL CONSTRAINT FK_PROVIDER_PRODUCTS FOREIGN KEY
	REFERENCES Providers,
)

CREATE TABLE Product_Sale
(
	ID INT PRIMARY KEY IDENTITY,
	DATA_VENDA DATETIME DEFAULT GETDATE() NOT NULL,
	VALOR FLOAT NOT NULL,
	CLIENTEID INT NOT NULL CONSTRAINT FK_CLIENT_PRODUCT_SALE FOREIGN KEY REFERENCES Customers,
	USERID INT NOT NULL CONSTRAINT FK_USER_PRODUCT_SALE FOREIGN KEY REFERENCES Users
)

CREATE TABLE Sale_Items
(
	ID INT PRIMARY KEY IDENTITY,
	PRODUCTID INT NOT NULL,
	CONSTRAINT FK_PRODUCT_SALE_ITEM FOREIGN KEY (PRODUCTID) 
	REFERENCES Products,
	QUANTIDADE INT NOT NULL, 
	VENDAID INT NOT NULL CONSTRAINT FK_SALE_SALE_ITEMS FOREIGN KEY
	REFERENCES Product_Sale,
	ATIVO BIT DEFAULT 1 NOT NULL,
)

